build: upgrade to edc version to 0.8.2-SNAPSHOT (DRAFT)
eclipse-edc/Technology-HuaweiCloud pull request #58
Opened 2024-09-06 10:44 UTC by ahmetuyanikdev

## What this PR changes/adds

Changed edc version to 0.8.2-SNAPSHOT
Fixed compile and build issues
Adjusted testcases and verified functionality

## Why it does that

Edc version upgrade for Huawei Cloud Project

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2024-09-11 11:44 UTC, janpmeyer requested changes

2024-09-11 11:44 UTC, janpmeyer commented on e2e-tests/src/test/java/com/huawei/cloud/tests/OtcTransferEndToEndTest.java
> +            assertThat(TransferProcessStates.valueOf(state).code()).isGreaterThanOrEqualTo(STARTED.code());
Test needs to wait for the TransferProcess to be completed.
So this Test is not valid

2024-09-13 10:03 UTC, janpmeyer requested changes
Just replace the Two Test for can Handle with a Test for the Support Method.

The rest looks good to me.

2024-09-13 10:03 UTC, janpmeyer commented on extensions/data-plane/data-plane-obs/src/test/java/com/huawei/cloud/transfer/obs/ObsDataSinkFactoryTest.java
Add Test for Support Method instead

2024-09-13 10:03 UTC, janpmeyer commented on extensions/data-plane/data-plane-obs/src/test/java/com/huawei/cloud/transfer/obs/ObsDataSourceFactoryTest.java
> -    @Test
Add Test for Support Method instead

2024-09-13 11:01 UTC, ahmetuyanikdev commented on extensions/data-plane/data-plane-obs/src/test/java/com/huawei/cloud/transfer/obs/ObsDataSinkFactoryTest.java
test method adjusted by support method

2024-09-16 06:47 UTC, ndr-brt approved these changes
please fix dependencies and we'll merge it

2024-09-16 10:43 UTC, ahmetuyanikdev commented
> please fix dependencies and we'll merge it

dependecies fixed.

2024-09-16 11:48 UTC, merged