release: add new build workflow
eclipse-edc/Technology-HuaweiCloud pull request #61
Opened 2024-09-11 13:16 UTC by mehmetihsansevinc

## What this PR changes/adds

_Added nightly.yaml workflow._

## Why it does that

_Builds and publishes at nights._

2024-09-16 06:50 UTC, ndr-brt commented on .github/workflows/verify.yaml
> +    if: ${{ inputs.skip-dependency-check != 'true' }}
no need for this, dependency-check won't run on scheduled workflows anyway (ref. https://github.com/eclipse-edc/.github/blob/dfb2f1c61348c41d35003b7ab04fc1dd33655077/.github/workflows/dependency-check.yml#L28)

2024-09-19 06:29 UTC, ndr-brt requested changes
old comment still not resolved

2024-09-19 07:06 UTC, mehmetihsansevinc commented
> old comment still not resolved

skip dependency check line removed

2024-09-19 07:43 UTC, ndr-brt requested changes
please re-request the review after you address a change, so I get notified, thanks

2024-09-19 07:43 UTC, ndr-brt commented on .github/workflows/verify.yaml
> +        default: 'false'
also this is not needed

2024-09-19 08:31 UTC, mehmetihsansevinc commented on .github/workflows/verify.yaml
> +        default: 'false'
Inputs removed.

2024-09-19 08:34 UTC, ndr-brt approved these changes
LGTM

2024-09-19 08:39 UTC, merged